[package]
name = "botbattle_agent_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
extism-pdk = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.127"

[lib]
crate-type = ["cdylib"]